{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww38200\viewh21600\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 esphome:\
  name: temhum\
\
esp8266:\
  board: nodemcuv2\
\
# Enable logging\
logger:\
\
# Enable Home Assistant API\
api:\
  encryption:\
    key: \'93YOUR ENCRYPTION KEY\'94\
\
ota:\
  password: \'93YOURPASSWORD\'94\
\
wifi:\
  ssid: !secret wifi_ssid\
  password: !secret wifi_password\
\
  # Enable fallback hotspot (captive portal) in case wifi connection fails\
  ap:\
    ssid: "Temhum Fallback Hotspot"\
    password: "yk5maJlHtACz"\
\
captive_portal:\
\
sensor:\
  - platform: dht\
    pin: D2\
    temperature:\
      name: "Living Room Temperature"\
    humidity:\
      name: "Living Room Humidity"\
    update_interval: 20s\
    \
switch:\
  - platform: gpio\
    pin: GPIO13\
    name: light_switch}